### PR TITLE
Updated/New Composer support for Net_SmartIRC

### PR DESCRIPTION
**Pull request by till**
See diff for full changes

### CODE REVIEW

**Comment by glensc** [comment]
@garrettw could you please publish on packagist.org as well?

https://packagist.org/packages/pear/

**Comment by garrettw** [comment]
Unfortunately I don't have enough rights in the PEAR organization on here or on Packagist to do that. @cweiske - @till - @CloCkWeRX -- any of you know about this?

**Comment by till** [comment]
I added it to packagist and enabled the service integration. HTH!

**Comment by garrettw** [comment]
@till Thanks a ton!

**Comment by meebey** [comment]
Thank you guys for taking care of Net_SmartIRC, highly appreciated! @garrettw @till

**Comment by garrettw** [comment]
@meebey It's my pleasure. I know there aren't many people who still use PEAR or this library, but as long as there are some, I'll do what I can to keep this usable. Why do I care? Well, I consider this the first real, working library (that people actually use) that I've had the privilege of maintaining.

**Pull request merged**
