### PR TITLE
Notice fixes

### PR DESCRIPTION
**Pull request by glensc**
see commit messages for details

### CODE REVIEW

**Comment by glensc** [comment]
that only variables can be returned as reference. the problem is that if you do not return, then engine adds `return null` behavior, and `null` is not a variable, so...

i initially made dummy variable, but then i remade this to actually make sense not just workaround.

otherwise, i'd say drop all method references that return objects, objects are always as reference in php 5. but that would break php4 compatibility.

**Comment by garrettw** [comment]
PHP4 compatibility is not a concern at this point, as the library already requires PHP 5.3.

**Comment by xvilo** [comment]
@glensc I want to voice my appreciation for both PR's. Thank you :) 👍

**Comment by garrettw** [comment]
@xvilo Don't hesitate to report any issues you may come across!

**Comment by glensc** [comment]
btw, i also filed bug with question. as issues disabled in github repo, had to report to pear: https://pear.php.net/bugs/bug.php?id=23746

**Comment by garrettw** [comment]
I don't have control over that, but issues are disabled here so that everything stays in one place. However I do concede that using GitHub issues would be more convenient in some ways.

Thanks for telling me.

**Pull request merged**
