### PR TITLE
fix composer autoload path

### PR DESCRIPTION
**Pull request by glensc**
it was somewhy broken in 2974536888eed22501abb50fd19264c11ef608ac

commit message gives no clue why the change was necessary.

reproducer here: https://gist.github.com/glensc/98c25958f519203ad58b9f6de76c3f75 
```
git clone https://gist.github.com/glensc/98c25958f519203ad58b9f6de76c3f75 pull-8
cd pull-8
composer install
./test.php
```

This PR also excludes 5MiB of docs not needed to be installed with composer. if there's still such wish they can clone repo directly or use prefer-source option.

also excludes generated cache `docs/HTML/phpdoc-cache-*`, adds to `.gitignore`.

```
    $ du vendor/pear/net_smartirc/
    56K     vendor/pear/net_smartirc/Net/SmartIRC
    144K    vendor/pear/net_smartirc/Net
    196K    vendor/pear/net_smartirc/
```

the test also demonstrates one other problem visible with composer: `$SMARTIRC_nreplycodes` does not get initialized if the `Net/SmartIRC/defines.php` file is included in non-global scope, like composer autoloader does that. my workaround is to import `$SMARTIRC_nreplycodes` to scope and load defines file first.

cc @garrettw

### CODE REVIEW

**Comment by garrettw** [comment]
Admittedly I've not used Composer with this library. Till Klampaeckel threw a composer.json file in here back when I was refactoring the library for the 1.1.0 release, and I just didn't pay much mind to it, knowing that this package is not on Packagist. However, at some point I tweaked the package's file structure, thinking I was improving it, and that change in 1.1.7 was probably to account for that. But then eventually I changed the file structure back when I realized my mistake, but I didn't remember to fix composer.json. So it was an oversight on my part.

All of your changes look like they should be good -- thanks!

**Comment by glensc** [comment]
could you please tag a release here. as i intend to make release in another project, which bundles the composer vendor. and it would be useless if the autoloading is broken...

if curious, then the project is here: https://github.com/eventum/irc-bot

**Comment by garrettw** [comment]
Yes, I already planned to do that -- maybe later today.

**Comment by glensc** [comment]
what's do difficult to make the release?

sorry ahead for being annoying...

**Comment by glensc** [comment]
using via repository type=pear to be able to release the package: https://github.com/eventum/irc-bot/commit/9220328703aa8b968d8d2055dda0698a6c1503ab

**Comment by garrettw** [comment]
I just wanted to resolve the bug report you made on the PEAR site before making a release.

**Comment by glensc** [comment]
the release is not appearing in packagist even if it's present as git tag in github

- https://github.com/pear/Net_SmartIRC/releases/tag/v1.1.12
- https://packagist.org/packages/pear/net_smartirc

**Comment by garrettw** [comment]
I have no control over that. @till @CloCkWeRX @cweiske any idea?

**Comment by ashnazg** [comment]
@garrettw I'll take a look.

**Comment by xvilo** [comment]
You have to setup packagist with the repo or manually update packagist.

**Comment by ashnazg** [comment]
I'm just waiting for @till to grant me access to it on packagist... the hook is ready to go.

**Comment by glensc** [comment]
[1.1.13](https://packagist.org/packages/pear/net_smartirc#v1.1.13) is now in packagist.

**Pull request merged**
